-- INCognito - esquema Supabase listo para configurar
-- Ejecuta este archivo completo en Supabase > SQL Editor.
-- Luego configura SOLO js/supabase-config.js.
-- No uses service_role en la aplicación.

create extension if not exists pgcrypto;

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check(char_length(username) between 3 and 24),
  bio text not null default '' check(char_length(bio)<=120),
  age integer check(age is null or age between 13 and 120),
  avatar_url text,
  discoverable boolean not null default true,
  notifications_enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.friend_requests(
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(sender_id,receiver_id),
  check(sender_id<>receiver_id)
);

create table if not exists public.friendships(
  id bigint generated by default as identity primary key,
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_a,user_b),
  check(user_a<>user_b)
);

create table if not exists public.messages(
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '' check(char_length(body)<=5000),
  image_url text,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check(char_length(body)>0 or image_url is not null)
);

create index if not exists messages_pair_idx on public.messages(sender_id,receiver_id,created_at desc);
create index if not exists messages_receiver_idx on public.messages(receiver_id,created_at desc);
create index if not exists requests_receiver_idx on public.friend_requests(receiver_id,status,created_at desc);

alter table public.profiles enable row level security;
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
alter table public.messages enable row level security;

drop policy if exists profiles_read_discoverable on public.profiles;
create policy profiles_read_discoverable on public.profiles for select to authenticated using(discoverable=true or id=auth.uid());
drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles for insert to authenticated with check(id=auth.uid());
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());

drop policy if exists requests_read_participants on public.friend_requests;
create policy requests_read_participants on public.friend_requests for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
drop policy if exists requests_insert_sender on public.friend_requests;
create policy requests_insert_sender on public.friend_requests for insert to authenticated with check(sender_id=auth.uid());
drop policy if exists requests_update_receiver on public.friend_requests;
create policy requests_update_receiver on public.friend_requests for update to authenticated using(receiver_id=auth.uid()) with check(receiver_id=auth.uid());

drop policy if exists friendships_read_participants on public.friendships;
create policy friendships_read_participants on public.friendships for select to authenticated using(user_a=auth.uid() or user_b=auth.uid());

drop policy if exists messages_read_participants on public.messages;
create policy messages_read_participants on public.messages for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
drop policy if exists messages_insert_sender on public.messages;
create policy messages_insert_sender on public.messages for insert to authenticated with check(sender_id=auth.uid());
drop policy if exists messages_update_receiver on public.messages;
create policy messages_update_receiver on public.messages for update to authenticated using(receiver_id=auth.uid()) with check(receiver_id=auth.uid());

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,username)
  values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)))
  on conflict(id) do update set username=excluded.username;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.accept_friend_request(request_id bigint)
returns void language plpgsql security invoker
as $$
declare r public.friend_requests;
begin
  select * into r from public.friend_requests where id=request_id and receiver_id=auth.uid() for update;
  if not found then raise exception 'Solicitud no encontrada'; end if;
  update public.friend_requests set status='accepted',updated_at=now() where id=request_id;
  insert into public.friendships(user_a,user_b)
  values(least(r.sender_id,r.receiver_id),greatest(r.sender_id,r.receiver_id))
  on conflict(user_a,user_b) do nothing;
end;
$$;

-- Si quieres usar fotos reales desde Supabase Storage, crea un bucket público/privado llamado profile-images
-- y aplica políticas de Storage acordes a tu modelo de seguridad. Esta app no expone service_role.
